[package]
name = "infrastructure_utilities"
version = "0.1.0"
edition = "2021"
description = "Infrastructure layer: Utilities - common helper functions"
license = "Apache-2.0"
authors = ["Erlang/OTP Rust Conversion"]

[dependencies]
entities_data_handling = { path = "../../entities/entities_data_handling" }
entities_utilities = { path = "../../entities/entities_utilities" }
entities_process = { path = "../../entities/entities_process" }
malachite = "0.7"
num-traits = "0.2"
num_cpus = "1.16"
flate2 = "1.0"
zstd = "0.13"
# Note: num-rational removed - now using BigRational from entities_utilities
# Note: ruzstd removed - using zstd crate for both compression and decompression

