[package]
name = "usecases_bifs"
version = "0.1.0"
edition = "2021"
description = "Use Cases layer: Built-in functions - regex, checksum, trace, etc."
license = "Apache-2.0"
authors = ["Erlang/OTP Rust Conversion"]

[dependencies]
entities_data_handling = { path = "../../entities/entities_data_handling" }
entities_utilities = { path = "../../entities/entities_utilities" }
entities_io_operations = { path = "../../entities/entities_io_operations" }
# Checksum algorithms
crc32fast = "1.3"
adler = "1.0"
md5 = "0.7"
digest = "0.10"
# Regular expressions
regex = "1.12"

