[package]
name = "frameworks_utilities"
version = "0.1.0"
edition = "2021"
description = "Frameworks layer: Utilities - system utilities"
license = "Apache-2.0"
authors = ["Erlang/OTP Rust Conversion"]

[dependencies]
entities_data_handling = { path = "../../entities/entities_data_handling" }

