[package]
name = "adapters_ets_tables"
version = "0.1.0"
edition = "2021"
description = "Adapters layer: ETS tables debugging"
license = "Apache-2.0"
authors = ["Erlang/OTP Rust Conversion"]

[dependencies]
entities_data_handling = { path = "../../entities/entities_data_handling" }

